### ISSUE TITLE
Allow TCP connections through tunnel

### ISSUE THREAD

**Issue by silasb** [aptible/docker-influxdb#4]
I'm looking to backup our InfluxDB instance and noticed that we can't tunnel to the TCP interface.

Did investigating and noticed that `template/influxdb.conf.template` doesn't have a global `bind-address` part.

It'd be super nice to do backups via https://docs.influxdata.com/influxdb/v1.5/administration/backup_and_restore/

**Comment by krallin** [comment]
There is no authentication (or encryption, AFAIK) on the RPC TCP interface in InfluxDB, so we can't reasonably support this for the time being.

See: https://github.com/influxdata/influxdb/issues/7639

**Comment by krallin** [comment]
> Doesn't a aptible db:tunnel setup a connection through the bastion layer. If I understand correctly the connection to the bastion layer is through a SSH tunnel.

That is correct. However, it doesn't change the fact that you have an RPC endpoint running with no authentication whatsoever on your private network.

Yes, that service can only be accessed from clients in your private network _or_ through a tunnel, but this remains too big of a footgun, notably when you consider that on shared-tenancy stacks (i.e. non-production), your network isn't actually private (which is why they're not for production apps). 

Besides, it's possible to expose Enclave databases on the public internet through [Database Endpoints](https://www.aptible.com/documentation/enclave/reference/databases/endpoints.html), which will, again, be a major problem if that service does not support any form of authentication. 

> While influxDB doesn't support encryption over their RPC TCP layer we'd already be secure going through the bastion layer?

That depends. If you're targeting HIPAA compliance and storing PHI in InfluxDB, you _might_ be secure, but you'd still be in violation of your BAA with us.

Indeed, `aptible db:tunnel` essentially gets you a secure, encrypted connection onto your private network's bastion layer in Enclave. However, you're still going to have a regular connection from that layer to the RPC service on your database (which is presumably running on a different service), and _that_ connection will not have encryption.

Unencrypted traffic on an internal network might be acceptable from a security perspective, but that's actually not allowed by our upstream providers if that traffic is PHI (presumably because they want to make sure PHI is never captured by network logging, etc.), and therefore not allowed by us either.

> Also, the same kind of TCP connection is allowed through MySQL with the `aptible-nossl` user.

Yes, and even though we document that this user shouldn't be used for sensitive data in multiple places, we occasionally encounter users doing so. As such, we're not particularly eager to introduce the same thing here.

---

In any case, you're focusing on encryption here, but that's not really the big picture. The big picture  is that this service does not support any kind of authentication. Exposing such a service on your network is hardly ever going to be safe, and can be extremely unsafe in certain configurations (e.g. shared-tenancy stacks, database endpoints). 

As a hosting provider, it's our responsibility to make sure we don't expose major footguns like this to our users, which is why we can't expose this RPC service.

**Comment by silasb** [comment]
Wow.  Wasn't expecting such a response.  Thanks for helping me understand.  :)

AFAIK this doesn't appear on their radar. :(
